# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/jessie64"
  config.vm.network :forwarded_port, guest: 80, host: 80, auto_correct: true
  config.vm.network :forwarded_port, guest: 8080, host: 8080, auto_correct: true
  config.vm.network :forwarded_port, guest: 8081, host: 8081, auto_correct: true

  config.vm.provision "shell", inline: <<-SHELL
    apt-add-repository -y ppa:ansible/ansible
    apt-get update
    apt-get install -y ansible
  SHELL

end
